apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-control
  template:
    metadata:
      labels:
        app: drone-control
    spec:
      containers:
        - name: control
          image: drone-control:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: drone-control
spec:
  selector:
    app: drone-control
  ports:
    - port: 8081
      targetPort: 8081
